### ISSUE TITLE
ValueError is occurred when running score_slg.py

### ISSUE THREAD

**Issue by lifefeel** [seokhwankim/dstc5#1]
Hi. I'm getting an error when I try to run score_slg.py.

I'm using in Ubuntu 14.04, python 2.7 and scikit-learn==0.16.0

How can I solve it?

```
$ python scripts/score_slg.py --dataset dstc5_dev --dataroot data/ --jsonfile slg.baseline.tourist.json --scorefile slg.baseline.tourist.score.csv --roletype TOURIST
Loading training instances ... /usr/local/lib/python2.7/dist-packages/sklearn/neighbors/base.py:185: UserWarning: cannot use tree with sparse input: using brute force
  warnings.warn("cannot use tree with sparse input: "
Done
Loading testing instances ... Done
Done
Found no errors, trackfile is valid
Loading AM model
Traceback (most recent call last):
  File "scripts/score_slg.py", line 75, in <module>
    main(sys.argv)
  File "scripts/score_slg.py", line 44, in main
    stats['generated']['all'] = Stat_BLEU_AM_FM('cn')
  File "/home/auc/dstc5/scripts/stat_classes.py", line 97, in __init__
    self.cs = calcScoresBleuAMFM(LANGUAGE=lang)
  File "/home/auc/dstc5/scripts/calc_amfm_bleu.py", line 118, in __init__
    self.vs = VSM(am_full_matrix, self.opt_am_size)
  File "/home/auc/dstc5/scripts/calc_amfm_bleu.py", line 54, in __init__
    self.load(model_file)
  File "/home/auc/dstc5/scripts/calc_amfm_bleu.py", line 86, in load
    self.am = joblib.load(name_model + '.h5')
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 418, in load
    unpickler = ZipNumpyUnpickler(filename, file_handle=file_handle)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 307, in __init__
    mmap_mode=None)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 265, in __init__
    self.file_handle = self._open_pickle(file_handle)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 310, in _open_pickle
    return BytesIO(read_zfile(file_handle))
  File "/usr/local/lib/python2.7/dist-packages/sklearn/externals/joblib/numpy_pickle.py", line 65, in read_zfile
    length = int(length, 16)
ValueError: invalid literal for int() with base 16: '0x789baf           x'
```

**Comment by seokhwankim** [comment]
It's caused by a bug in the older versions of joblib.
Could you please test it again not with the one from Ubuntu repository, but the up-to-date version?
It works well for me with the pip installation.

**Comment by lifefeel** [comment]
Thank you. I update scikit-learn to 0.17.0 and it runs well.

But, another problem is occurred with scikit-learn 0.17.0 when runs baseline_sap.py

```
$ python scripts/baseline_sap.py --trainset dstc5_train --testset dstc5_dev --dataroot data --roletype GUIDE --modelfile sap.baseline.guide.model --outfile sap.baseline.guide.json
Loading training instances ... Done
Traceback (most recent call last):
  File "scripts/baseline_sap.py", line 215, in <module>
    main(sys.argv)
  File "scripts/baseline_sap.py", line 158, in main
    sap.train(args.modelfile)
  File "scripts/baseline_sap.py", line 109, in train
    sa_labels = self.__speech_act_lb.fit_transform(sa_labels)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/base.py", line 455, in fit_transform
    return self.fit(X, **fit_params).transform(X)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/preprocessing/label.py", line 300, in fit
    self.y_type_ = type_of_target(y)
  File "/usr/local/lib/python2.7/dist-packages/sklearn/utils/multiclass.py", line 251, in type_of_target
    raise ValueError('You appear to be using a legacy multi-label data'
ValueError: You appear to be using a legacy multi-label data representation. Sequence of sequences are no longer supported; use a binary array or sparse matrix instead.
```

**Comment by seokhwankim** [comment]
It has been fixed by https://github.com/seokhwankim/dstc5/commit/aa0ad4d506f269eb2c6ccb2a9354719f0c51b25c

**Comment by lifefeel** [comment]
It works well. Thanks.
